version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: pip
    directory: /assetcc
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /assetcc
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
